== Arquillian Droidium extensions

This is the home of the following extensions for Arquillian testing platform:

=== Arquillian Droidium container

Implementation of Arquillian container abstraction for Android devices.

=== Arquillian Droidium Web

Extension for supporting web testing for Droidium container. You need this 
when you want to functionaly test your application on mobile devices.
Web extension relies on Selenium project from where it takes Android server APK.

=== Arquillian Droidium Native

Extension for supporting testing of native applications for Droidium container. You 
need this extension when you want to functionally test your native Android application.
Native extension relies on http://dominikdary.github.io/selendroid/[Selendroid] project 
from where it takes Selendroid server APK.

Every extension has its own README and configuration documentation. You are 
welcome to check them in their respective directories.

=== How to install Arquillian Droidium

`mvn install`

Archetype projects are installed as well as extensions themselves so you have two options how to boostrap 
your Android mobile testing:

* copy over some test in `tests` directory according to your testing needs and modify it subsequently
* generate your project from provided archetypes in `archetypes` directory

=== Android SDK issues

This project uses ddmlib of version 22.1.3. You can check the versions of ddmlib library http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.android.tools.ddms%22%20AND%20a%3A%22ddmlib%22[here]. When you want to change the version of ddmlib manually, just rewrite that property in the root `pom.xml` of the project called `version.ddmlib`, however it does not mean that project will be compilable every time since there can be changes in the ddmlib API over time which 
will not be compatible with Arquillian Droidium.

Due to https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=58424[this bug] which is already resolved in upstream but waits to be released, you are obliged to use the older version of `adb` command from your Android SDK tooling. It is known that version of `adb` which works properly is found in Android platform tools of version 22.0.1.

=== Take screenshots during your tests

That is right, you can take screenshots as you test by very simple way. You are welcome to check 
the project which shows how to do it directly in your test methods in https://github.com/arquillian/arquillian-droidium/tree/master/tests/arquillian-droidium-screenshooter-test-01[screenshooter demo] in `tests` directory.

=== How to test extensions?

When you are doing `mvn clean install`, some tests are executed automatically. These 
tests do not need any special profile to be chosen and they work out of box.

Tests for Arquillian Droidium resides mainly in `droidium-container`.
Android specific tests are skipped by default since they require Android SDK to 
be installed on target host.

If you want to try them, you *have to* have Android SDK installed locally and 
`$ANDROID_HOME` has to point to the installation directory. 
Next, you have to select specific profile. Android specific tests are divided 
into two profiles. The first one is called _automatic_ and even it uses 
Android SDK, it does not need any additional intervention from a tester point of view.
You execute _automatic_ tests like:

`mvn clean test -Pandroid-automatic`

Tests which are expecting to have some Android emulator already started are triggered by

`mvn clean test -Pandroid-manual-emulator`

Finally, there are tests which are expecting to have real Android device 
connected via USB cable to your computer. You trigger this profile by executing:

`mvn clean test -Pandroid-manual-real`

IMPORTANT: Please consult testing profiles in `droidium-container/arquillian-droidium-container-impl/pom.xml` to know exactly what kind of emulators you have to have and what possibilities you have when using AVDs or ports different from the default ones.

=== Proof-of-concept tests

Test projects which are reflecting the very basic setup to bootstrap your 
testing experience are placed in `tests` directory.

=== How to contribute?

You are very welcome to contribute to this set of extensions in any way. It is very welcome to test 
possibilities of testing - simulate own scenarios and so on.

You should follow these steps:

* Use separate branch for every feature you are adding.
* Use IDE configuration files for JBoss located https://github.com/jboss/ide-config[here].
* Test your contribution and write tests whenever possible and necessary.
* When you are writing some testing project, please put it in `tests` directory and follow naming rules as already shown.

Thank you!

=== Contact

This set of extensions is being developed as a part of Google Summer of code 2013.

You are welcome to check development blog of 

* http://miklosovic.net[Stefan Miklosovic]
* http://toseter.ru/[Aleksey Shilin]
