== Arquillian Droidium extensions

This is the home of the following extensions for Arquillian testing platform:

=== Arquillian Droidium container

Implementation of Arquillian container abstraction for Android devices.

=== Arquillian Droidium Web

Extension for supporting web testing for Droidium container. You need this 
when you want to functionaly test your application on mobile devices.
Web extension relies on Selenium project from where it takes Android server APK.

=== Arquillian Droidium Native

Extension for supporting testing of native applications for Droidium container. You 
need this extension when you want to functionally test your native Android application.
Native extension relies on http://dominikdary.github.io/selendroid/[Selendroid] project 
from where it takes Selendroid server APK.

*Every extension has its own very detailed and deep README and configuration documentation in its respective directory.*

=== How to install Arquillian Droidium

`mvn clean install`

=== How to use Android containre and web and native plugins?

Every extension has its own README and configuration documentation in its respective directory.
You can find archetypes for native and web testing in archetype directory so you can boostrap your 
testing process significantly. You can also take a look into _tests_ directory. There is bunch of 
example projects how to use it with very deep documentation.

=== How to generate Javadoc?

`mvn javadoc:aggregate`
