== Arquillian Droidium - ftesting of Android done right

This is the home of the following extensions for Arquillian testing platform:

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-container[Arquillian Droidium container]

Implementation of Arquillian container abstraction for Android devices. By this Arquillian container adapter, you can execute tests 
dealing with Android devices where Android device is considered to be just another Arquillian container.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-platform[Arquillian Droidium platform]

This tiny extension provides core Android platform configuration on which Droidium container depends.

=== https://github.com/arquillian/arquillian-droidium/blob/master/droidium-native/[Arquillian Droidium Native]

Extension for supporting testing of native applications for Droidium container. You 
need this extension when you want to functionally test your native Android application.
Native extension relies on http://dominikdary.github.io/selendroid/[Selendroid] project 
from where it takes Selendroid server APK.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-recorder[Arquillian Droidium Recorder]

By this extension, you can make videos of Android devices while you are executing tests.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-screenshooter[Arquillian Droidium Screenshooter]

By this extension, you can take screenshots of Android devices while you are executing tests.

=== Examples

[source,java]
----
@RunWith(Arquillian.class)
@RunAsClient
public class AndroidContainerTest {

    // injected abstraction of your Android device
    @ArquillianResource
    AndroidDevice android;

    // APK will be deployed to android device
    // upon Android container startup
    @Deployment
    public static Archive<?> createAndroidDeployment() {
        return ShrinkWrap.createFromZipFile(
            JavaArchive.class, new File(my.apk));
    }   

    @Test
    public void test01() {
        assertTrue(android != null);

        String sn = android.getSerialNumber();
        String avdName = android.getAvdName();
        
        Assert.assertTrue(android.isOnline());
        Assert.assertFalse(android.isOffline());

        boolean emulator = android.isEmulator();

        // command and package management
        android.executeShellCommand("execute on android");
        android.createPortForwarding(localPort,remotePort);
        android.installPackage();
        android.uninstallPackage();
        android.isPackageInstalled("package name");

        // taking screenshots and record videos
        Screenshot screenshot = android.getScreenshot();
        
        android.startRecording(remoteFilePath, options);
        Video video = android.stopRecording(localFilePath);

        // push, pull and remove file to and from device
        android.push(localFilePath, remoteFilePath);
        android.pull(remoteFilePath, localFilePath);
        android.remove(remoteFilePath);
    }   
}
----

Complete information how to use Android container can be found https://github.com/arquillian/arquillian-droidium/blob/master/droidium-container/README.adoc[here].

[source,java]
----
@RunAsClient
@RunWith(Arquillian.class)
public class NativeAndroidTestCase {

    @Drone
    AndroidDriver mobile;

    @Deployment
    @Instrumentable // instruments APK by Selendroid server
    public static Archive<?> getDeployment() {
        return ShrinkWrap.createFromZipFile(JavaArchive.class,
            new File("my.apk"));
    }

    @Test
    public void test() {
        mobile.startActivity("my.fqcn.of.activity");
    }
----

Complete information how to use Android Native plugin for ftesting can be found https://github.com/arquillian/arquillian-droidium/blob/master/droidium-native/README.adoc[here].

=== https://github.com/arquillian/arquillian-recorder[Arquillian Recorder integration]

This extension builds on top of https://github.com/arquillian/arquillian-recorder[Arquillian Recorder] so by using above recorder and screenshooter extensions, these resources will appear in resulting exporter report in e.g. html file.

=== Runtime dependencies

You have to have installed https://developer.android.com/sdk/index.html[Android SDK] locally on your machine and you have to set it up fully.

Be sure you set all environment properties like +ANDROID_HOME+ and +ANDROID_SDK_HOME+m +JAVA_HOME+ and +HOME+.

You have to have Java installed locally as well. Droidium is developed against Java 1.6.

=== Example projects

Example project which show various usecases of Droidium are the part of this project and can be found here:

https://github.com/arquillian/arquillian-droidium/tree/master/tests[Droidium demos]

You can generate your own project via archetypes. They can be found here

https://github.com/arquillian/arquillian-droidium/tree/master/archetypes[Droidium archetypes]

=== How to install Arquillian Droidium?

`mvn clean install`

=== How to use Android container native application testing?

Please find respective README and configuration documentation in its respective directory.
You can find archetypes for native testing in archetype directory so you can boostrap your 
testing process significantly faster. You can also take a look into _tests_ directory. There is bunch of 
example projects how to use it with very deep documentation.

=== How to generate Javadoc?

`mvn javadoc:aggregate`

=== JIRA & Issue tracker

You are welcome to raise your issues at JBoss JIRA for Droidium component:

https://issues.jboss.org/browse/ARQ/component/12314143[JBoss JIRA - Droidium component]
