== Arquillian Droidium extensions

This is the home of the following extensions for Arquillian testing platform:

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-container[Arquillian Droidium container]

Implementation of Arquillian container abstraction for Android devices. By this Arquillian container adapter, you can execute tests 
dealing with Android devices where Android device is view just as another Arquillian container.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-platform[Arquillian Droidium platform]

This tiny extension provides core Android platform configuration on which Droidium container depends.

=== https://github.com/arquillian/arquillian-droidium/blob/master/droidium-native/[Arquillian Droidium Native]

Extension for supporting testing of native applications for Droidium container. You 
need this extension when you want to functionally test your native Android application.
Native extension relies on http://dominikdary.github.io/selendroid/[Selendroid] project 
from where it takes Selendroid server APK.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-recorder[Arquillian Droidium Recorder]

By this extension, you can make videos of Android devices while you are executing tests.

=== https://github.com/arquillian/arquillian-droidium/tree/master/droidium-screenshooter[Arquillian Droidium Screenshooter]

By this extension, you can take screenshots of Android devices while you are executing tests.

=== https://github.com/arquillian/arquillian-recorder[Arquillian Recorder integration]

This extension builds on top of https://github.com/arquillian/arquillian-recorder[Arquillian Recorder] so by using above recorder and screenshooter extensions, these resources will appear in resulting exporter report in e.g. html file.

=== Runtime dependencies

You have to have installed https://developer.android.com/sdk/index.html[Android SDK] locally on your machine and you have to set it up fully.

Be sure you set all environment properties like +ANDROID_HOME+ and +ANDROID_SDK_HOME+m +JAVA_HOME+ and +HOME+.

You have to have Java installed locally as well. Droidium is developed against Java 1.6.

=== Example projects

Example project which show various usecases of Droidium are the part of this project and can be found here:

https://github.com/arquillian/arquillian-droidium/tree/master/tests[Droidium demos]

You can generate your own project via archetypes both for native and web testing. They can be found here

https://github.com/arquillian/arquillian-droidium/tree/master/archetypes[Droidium archetypes]

=== How to install Arquillian Droidium?

`mvn clean install`

=== How to use Android container web and native testing?

Please find respective README and configuration documentation in its respective directory.
You can find archetypes for native and web testing in archetype directory so you can boostrap your 
testing process significantly. You can also take a look into _tests_ directory. There is bunch of 
example projects how to use it with very deep documentation.

=== How to generate Javadoc?

`mvn javadoc:aggregate`

=== JIRA & Issue tracker

You are welcome to raise your issues at JBoss JIRA for Droidium component:

https://issues.jboss.org/browse/ARQ/component/12314143[JBoss JIRA - Droidium component]
