= Arquillian Droidium

The aim of this document is to describe how to use Android container for Arquillian platform - Droidium. The reader can expect 
various use cases of arquillian.xml configuration as well as all needed artifact dependecies for Maven in order to 
be able to start some Android container successfuly.

== Concepts

The significant difference between ordinary container adapter for Arquillian and Android container is that while
using the ordinary one, you have to use only that one type of the container you are deploying the archives to. 
There is not the support for multiple container implementations in 1.x versions of Arquillian out of the box 
so you are normaly forced not to mix two different container adapter implementations together. This restriction is 
overriden by module _arquillian-droidium-multiple-containers_ via which it is possible to use ordinary 
container adapter e.g. JBoss AS with Android container adapter itself. Because of this, you can then deploy 
your web application into JBoss AS container and you test it on your mobile phone (emulator or physical device).

== Setup

When you want to use Droidium, you have to basically put into `pom.xml` just this dependency:

----
<dependency>
    <groupId>org.arquillian.container</groupId>
    <artifactId>arquillian-droidium-container</artifactId>
    <type>pom</type>
    <scope>test</scope>
    <version>${droidium.version}</version>
</dependency>
----

== Multiple containers extension

Arquillian Droidium container uses _arquillian-droidium-multiple-containers_ module in this repository. That module, while on the 
classpath, is able to register containers of various types, so you can mix two (three, four ...) different 
container implementations. This module has to know what container implementation stands for what container adapter.

In order to make the difference, Droidium tries to "guess" what container adapters are on the classpath.

=== Container selection

First of all, Droidium just tries to "guess" which configuration stands for which container adapter.

While guessing can be unsuccessful in the end, there is the ultimate solution how you can specify which container adapter 
stands for which container configuration in arquillian.xml. There is a property `adapterImplClass` which tells Droidium 
that container configuration is backed by container adapter which is implemented by that class. Let's see the example:

----
<group qualifier="containers" default="true">
    <container qualifier="jbossas">
        <configuration>
            <property name="adapterImplClass">
                org.jboss.as.arquillian.container.managed.ManagedDeployableContainer
            </property>
        </configuration>
    </container>
    <container qualifier="android">
        <configuration>
            <property name="adapterImplClass">
                org.arquillian.droidium.container.AndroidDeployableContainer
            </property>
        </configuration>
    </container>
</group>
----

When there are multiple containers specified and no `adapterImplClass` set, guessing in this sense means that Droidium sets 
container configuration to container adapter based on the container qualifier in the `container` element. It is sufficient that 
container qualifier just contains this string. For example:

[cols="2*", options="header"]
|===
|container qualifier |adapter class

|android
|org.arquillian.droidium.container.AndroidDeployableContainer

|droidium
|org.arquillian.droidium.container.AndroidDeployableContainer

|glassfish
|org.jboss.arquillian.container.glassfish.*

|jboss
|org.jboss.as.arquillian.container.*

|wildfly
|org.wildfly.arquillian.container.*

|eap
|org.jboss.as.arquillian.container.*

|openshift
|org.jboss.arquillian.container.openshift.*

|tomee
|org.apache.openejb.arquillian.*
|===

You have to provide `adapterImplClass` property per container configuration only when you are using more then one 
container adapter implementation on your classpath - as in given example above. When you are using Android container 
alone, you do not have to specify that property since it is the only class on the classpath which implements Arquillian container API.

Put it all together, you can use just Android container itself as:

----
<container qualifier="android">
    <configuration>
        <properties ...
    </configuration>
</container>
----

While Droidium tries to guess the container, Android container is recognized even it is not named like _android_ or _droidium_. In this case, 
it is sufficient that container contains some configuration property which is Droidium specific such as avdName, serialId, consolePort or emulatorOptions.

Right now, you can not use more than one Android container simultaneously.

== Basic usage

----
@RunWith(Arquillian.class)
@RunAsClient
public class ContainerTest {

    @ArquillianResource
    AndroidDevice android;

    @Deployment(testable = false)
    public static Archive<?> createArchive() {
        return // some ShrinkWrapDeployment
    }

    @Test
    public void test01() {
        assertTrue(android != null);
    }
}
----

== Android container is testing agnostic

Up to this point, you saw how container itself is configured but there are not _true_ tests.
It is because Android container _is not_ intended to test your code at all. The reason why Android container 
adapter implementation exists is that it provides common framework how Android device is 
started and shutted down. It treats device management of your emulator or physical device 
and it treats creation of AVD from scratch as well as management of Android SD cards which are used in 
connection with Android emulator.

=== Web testing
When you want to test web application (bundled as war/ear and deployed into application container as JBoss AS), 
you need to use plugin into Android container called *droidium-web* in this repository. Please consult README
there in order to know more. By this plugin, you can functionaly test your web application via WebDriver 
API from Selenium.

The basic workflow is very easy. You configure two containers in `arquillian.xml`. The first one is 
normal application container as JBoss AS, the second one is Android container. After that, you specify 
`@Deployment` for application container. That application is deployed there and finally you use 
WebDriver from Arquillian Graphene in order to do functional tests on your application but that application 
is viewed not from your desktop browser but from browser in you Android device.

Please consult README in *droidium-web* directory in order to get more information how to bootstrap your 
functional testing on Android platform.

=== Native testing
On the other hand, you can test your native Android application by writing some functional tests for it.
You have to use *droidium-native* plugin in this repository. Details how to test functionally your native 
Android application will be given in the README located in that plugin.

== Android container configuration

After seeing how to put Android container in `arquillian.xml`, the configuration of the Android container itself is 
following. The list of all properties and its meaning is described, accompanied with examples. The division 
between physical Android Device and emulator is done.

=== General properties

System properties overrides environment properties.

==== androidHome
===== default: $ANDROID_HOME

`androidHome` property holds the directory where your Android SDK is installed. It is not necessary to specify it 
since it is automatically read from the system environment property `$ANDROID_HOME` which can be easily exported 
as `export $ANDROID_HOME=/path/to/your/sdk` for the current shell or it can be put into `~/.bash_profile` to be 
persisted. It can be specified in rutime via `android.home` System property.

----
<configuration>
    <property name="androidHome">/path/to/your/android/sdk</property>
</configuration>
----

or from e.g. Maven point of view:

----
-Dandroid.home=/path/to/your/android/sdk
----

=== androidSdkHome
==== default: $ANDROID_SDK_HOME

This property tells where are e.g. your AVDs stored. By default. When this property is not set, it defaults to `$HOME` in 
`.android` directory. When you set this property e.g. to `target`, your AVDs will be created in `target` directory so 
after you clean your test, there is not any sign there was some Android used. You can use system property `android.sdk.home` as well.

----
<configuration>
    <property name="androidSdkHome">target</property>
</configuration>
----

==== javaHome
===== default: $JAVA_HOME

`javaHome` property sets the directory where your JDK installation is placed. It can be set similarly as `androidHome` property via
shell infrastructure. After setting this, it uses commands as `jarsigner` or `keytool` from there.

----
<configuration>
    <property name="javaHome">/path/to/your/java</property>
</configuration>
----

==== forceNewBridge
===== default: true

`forceNewBridge` boolean property specifies if Android Debug Bridge (ADB) should be forced to be created even it 
already is. It can have only `true` or `false` value. When not used, it is set to true.

----
<configuration>
    <property name="forceNewBridge">false</property>
</configuration>
----

==== ddmlibCommandTimeout
===== default: 20000

`ddmlibCommandTimeout` property says what is the timeout for ddmlib library which executes commands for your device. When 
it is low, in emulated or CI environment, default timeout (5000 milliseconds) can be not enough due to its slowness. In that 
case, try to raise the value of this property. It is measured in milliseconds. You can not set the timeout lower then 5000 ms.

----
<configuration>
    <property name="ddmlibCommandTimeout">60000</property>
</configuration>
----

==== adapterImplClass
===== default: org.arquillian.droidium.container.AndroidDeployableContainer

Specifies what is the implementation class of Arquillian Droidium container. You *have to* use this property 
when you place more then one Arquillian container adapter on the class path at time. For example, when you are 
doing web testing, you are using e.g. JBoss container. You are obliged to specify this property for every container 
adapter in configuration section in arquillian.xml with implementation class of adapter.

Note that you do not have to specify this property when you are using only Droidium container itself.

----
<group qualifier="containers" default="true">
 <container qualifier="android" default="true">
  <configuration>
   <property name="adapterImplClass">
     org.arquillian.droidium.container.AndroidDeployableContainer
   </property>
  </configuration>
 </container>
 <container qualifier="jbossas">
  <configuration>
   <property name="adapterImplClass">
    org.jboss.as.arquillian.container.managed.ManagedDeployableContainer
   </property>
  </configuration>
 </container>
</group>
----

=== Real Android Device Configuration

==== serialId
===== default: not defined

`serialId` property holds the identification number of your physical mobile phone or device (e.g. table). 
That number can be find out by command `adb devices -l` after your Android device is connected via usb cable to your computer.

----
<configuration>
    <property name="serialId">42583930325742351234</property>
</configuration>
----

=== Virtual Android Device Configuration

==== avdName
===== default: not defined

Name of Android Virtual Device you want to start. If there is no such device available, it will generate an AVD named by +avdName+ name. 
If left blank, an unique +avdName+ will be generated.

----
<configuration>
    <property name="avdName">my-avd</property>
</configuration>
----

==== abi
===== default: `x86`

Pretty straightforward. Which ABI your container should use. When you are going to create an AVD dynamically for a
+target+ and there is not such ABI available for that level, whatever comes first among +x86+, +armeabi-v7a+, +android-wear/armeabi-v7a+ or +mips+ is used.

----
<configuration>
    <property name="abi">armeabi-v7a</property>
    <property name="abi">android-wear/armeabi-v7a</property>
</configuration>
----

==== target
===== default: the highest pure Android API Level available

Sets your target you want to use when you are going to create emulator from scratch. Possible values for this property 
are the same as the output of +android list targets -c+. You can use integer value of API level you want to target as well. When you 
do not specify +abi+ property, it tries to match whatever available comes first among +x86+, +armeabi-v7a+, +android-wear/armeabi-v7a+  or +mips+ 
for that target. In case you use Google API target, it has ABI specified in it. When it is not there, it uses arm.

----
<configuration>
    <property name="target">18</property> // is the same as android-18
    <property name="target">android-18</property>
    <property name="target">Google Inc.:Google APIs:19</property> // uses armeabi-v7a
    <property name="target">Google Inc.:Google APIs x86:19</property> // uses x86
</configuration>
----

==== emulatorBootupTimeoutInSeconds
===== default: 120 seconds

Specifies timeout after which container is considered to be unsuccessfuly started. When emulator is not 
started after this amount of time, the whole test fails. It can be used as a prevention to wait for the 
start of the container for ever in case somehow hangs or your computer is slow to start it faster. 
The value has to be positive non-zero integer.

----
<configuration>
    <property name="emulatorBootupTimeoutInSeconds">180</property>
</configuration>
----

==== emulatorShutdownTimeoutInSeconds
===== default: 60 seconds

Similar as `emulatorBootupTimeoutInSeconds` but regarding of the emulator shutdown process. The value 
has to be positive non-zero integer.

----
<configuration>
    <property name="emulatorShutdownTimeoutInSeconds">45</property>
</configuration>
---- 

==== emulatorOptions
===== default: empty string

All other configuration switches you want to use for your emulator instance upon its start but there is not the configuration 
property for it. It is the string which is appended to the `emulator` command. Strings with quotes shoud work as 
well but its number has to be even. (They have to logically enclose some string).

----
<configuration>
    <property name="emulatorOptions">-memory 256 -nocache</property>
</configuration>
----

==== consolePort
===== default: not specified, selected by `emulator` automatically

Specifies which console port an emulator should use. It has to be even number in range 5554 - 5584. When this 
property is used and `adbPort` property is not, `adb` automatically selects as `adbPort` number `consolePort` + 1. 

----
<configuration>
    <property name="consolePort">5558</property>
</configuration>
----

==== adbPort
===== default: console port + 1

Specifies which adb port should emulator connect to. It has to be odd number in range 5555 - 5585.

----
<configuration>
    <property name="adbPort">5559</property>
</configuration>
----

==== adbServerPort
===== default: 5037

Specifies ADB server port against which should Droidium connect in order to parse emulators. It is +ANDROID_ADB_SERVER_PORT+ property from Droidium point of view.

----
<configuration>
    <property name="adbServerPort">5038</property>
</configuration>
----

==== droneHostPort
===== default: 14444

This property is used to set a port number on the localhost from where the communication to Android device will be carried out.
It is used in connection with web testing mainly (for sending REST calls from Graphene to Android server APK installed on the 
device) but it can be used for any other purposes. It is used as a port number for por forwarding command from Android debug bridge
(`adb`) on the host side.

==== droneGuestPort
===== default: 8080

The same as `droneHostPort` in principle but it treats port on device side.

== SD Card configuration

It is possible to use SD card while creating / using some emulator instance. 
When we are using more then one emulator and SD card is used, these emulators are 
using the same SD card which results in a clash. Creation of a SD card is backed by 
command `mksdcard` which is bundled in Android SDK. All inputs are validated. Size
constrains are the same as for the `mksdcard` itself and are checked for its 
validity on the container side.

Options you can use in connection with SD card configuration are as follows:

==== sdSize
===== default: 128M

Specifies that SD card of size `sdSize` is going to be used. In order to create SD card of size 512MB you have to
put this in the configuration:

----
<configuration>
    <property name="sdSize">512M</property>
</configuration>
----

==== sdCard
===== default: `android` specifies

Specifies filename where `sdCard` is placed or where it should be created when it does not exist. The suffix 
of the sdCard *has* to end with `.img`.

----
<configuration>
    <property name="sdCard">/tmp/my_sdcard.img</property>
</configuration>
----

==== sdCardLabel
===== default: generated randomly

Specifies label to use for a SD card we want to be created automatically. It does not have to be used.

----
<configuration>
    <property name="sdCardLabel">my_sdcard_label</property>
</configuration>
----

==== generateSDCard
===== default: false

Tells Arquillian that we want to generate card we specified. When this flag is used, the card is deleted after 
tests are done.

----
<configuration>
    <property name="generateSDCard">true</property>
</configuration>
----

== Logcat logging configuration

Arquillian Container comes with logcat support, which by default logs everything from logcat, that's of type 
`warning` and above, into `System.out` with a prefix `LOGCAT:`.

==== logLevel
===== default: W

Sets the level filter. Android supports following levels:

* `V` for verbose messages
* `D` for debug messages
* `I` for info messages
* `W` for warning messages
* `E` for error messages

If you set level to `V`, everything will be logged, if `W` then only warnings and errors.

----
<configuration>
    <property name="logLevel">D</property>
</configuration>
----

==== logType
===== default: output

Used to define what should be done with the logs read from logcat.

* `output` - print to System.out
* `logger` - log through Logger instance
* `file` - save into file
* `disable` - disable logcat support

----
<configuration>
    <property name="logType">file</property>
</configuration>
----

==== logFilePath
===== default: target/logcat.log

If `logType` is set to `file`, this is the path, where the output log file will be stored. Make sure this path 
is accessible and writable.

----
<configuration>
    <property name="logFilePath">target/logs/lolcat.log</property>
</configuration>
----

==== logPackageWhitelist
===== default: not defined

You can set, what would you like to always log, no matter of what. The whitelist is applied to process name, 
which for applications is a package name. The value can be comma separated list of rules, in which you can use 
`*` that will behave as regex's non-greedy expression `.*?`.

NOTE: If you set `logPackageWhitelist` and not `logPackageBlacklist`, it's assumed that you want to only log 
what's specified by whitelist, so the `logPackageBlacklist` will be set to `*`.

----
<configuration>
    <property name="logPackageWhitelist">io.selenium*,system_server,org.example.showtime</property>
</configuration>
----

==== logPackageBlacklist
===== default: not defined

What's not catched by whitelist is then passed to blacklist. It works exactly the opposite way, that means 
whatever matches is discarted. As mentioned in `logPackageWhitelist` description, when you set `logPackageWhitelist` 
but not `logPackageBlacklist`, it will automatically get set to `*`. If you don't want this behavior, 
just make sure you set `logPackageBlacklist` in your configuration to empty value. This way you declare that you 
really want the `logPackageBlacklist` to be empty.

----
<configuration>
    <property name="logPackageBlacklist">org.example.*,com.android.phone</property>
</configuration>
----

==== logSerialId
===== default: false

This flag is useful if you're about to test more than one device at a time. If you set this flag to `true`, 
the outcome varies by `logType`. For `output` and `logger`, it will add the serial id of device to the prefix 
`LOGCAT (serial-id):`. When the `file` logging is selected, the final log file name will contain the serial id 
before the extension (e.g. target/logcat.log will change to target/logcat.serial-id.log).

----
<configuration>
    <property name="logSerialId">true</property>
</configuration>
----

=== All following paramaters regarding debug keystore and its generation are subject of `keytool` command.

==== keystore
===== default: $ANDROID_SDK_HOME/.android/debug.keystore

Sets keystore to use for resigning packages after they are modified dynamically. Not resigning them 
would result into impossibility to install them to Android device since certificates would be different.
Debug key store is automatically created for you when it is not created yet, typically in `~/.android` or when you 
specifies keystore in `keystore` property and such keystore path does not exist.

----
<property name="keystore">/path/to/your/key/store</property>
----

==== storepass
===== default: "android"

----
<property name="storepass">storepass</property>
----

==== keypass
===== default: "android"

----
<property name="keypass">keypass</property>
----

==== alias
===== default: androiddebugkey

----
<property name="alias">somealias</property>
----

==== sigalg
===== default: SHA1withRSA

Tells what kind of signature algoritm to use for a debug keystore when it is created.

----
<property name="sigalg">MD5withSHA</property>
----

==== keyalg
===== default: RSA

Tells what kind of key algoritm to use for a debug keystore when it is created.

----
<property name="keyalg">some_other_keyalg</property>
----

==== tmpDir
===== default: java.io.tmpdir

Specifies where to do all repackaging operaions with Selendroid server and _aut_. All reconstruction, 
resigning and storing of APKs is done there. From the implementation point of view, all packages and 
directories are random UUID identifiers.

This directory is deleted by default where tests are finished. It can be changed via `removeTmpDir` 
property.

----
<property name="tmpDir">/path/to/tmp/dir</property>
----

==== removeTmpDir
===== default: true

Specifies if all temporary resources as repackaged Selendroid server should be removed by default.
Set it to false when you want to inspect what packages are going to be installed for debug purposes, 
however it is desired to remove this directory by default since it can occupy significant amount of 
space. For every test run, other working directory is created every time.

----
<property name="removeTmpDir">true|false</property>
----

== Connection logic of Android container

* If console port was specified but AVD name was not, we try to connect to running emulator which listens to specified port.
* If we fail to connect, {@link AndroidExecutionException} is thrown.
* If AVD name was specified but console port was not, we try to connect to the first running emulator of such AVD name.
* If both AVD name and console port were specified, we try to connect to this combination.
* If we fail to get device in all above steps:
** If AVD name was not specified, random AVD identifier is generated.
** If AVD is among erroneous AVDs, it will be deleted, created from scratch, started and deleted after test.
** If AVD is among non-erroneous AVDs, it will be started.
** If AVD is not present, it will be created and started and deleted after test

== SD card usage logic

Creation of SD card depends on the combination of a few facts. Let's check the logic:

* If generateSDCard property is specified
** If sdCard is not specified
*** Generate random sdCard identifier
*** Create the card and use it
** If sdCard is specified
*** If such sdCard already exists, use that card
*** Create such sdCard and use it
* If generateSDCard property is not specified
** If sdCard is not specified
*** use default system SD card from Android
** If sdCard is specified
*** If it exists, use it
*** If it does not exist, use default system one.
