= Arquillian Droidium Screenshooter

Droidium screenshooter is an extension to Arquillian platform which provides the possibility to take screenshots of your Android tests. The emulator window or device's display is screened. In order to use it, please place this artifact configuration into Maven dependencies.

Example of HTML report via https://github.com/arquillian/arquillian-recorder[Arquillian Recorder] which is embedded into screenshooter looks like http://devio.us/~stewe/report/arquillian_report.html[this].

== Making it part of your project

[source,xml]
----
<dependency>
    <groupId>org.arquillian.extension</groupId>
    <artifactId>arquillian-droidium-screenshooter</artifactId>
    <version>${version.droidium}</version>
</dependency>
----

== Settings

Following +arquillian.xml+ properties are supported within *screenshooter* qualifier:

|===
|Configuration Property|Description|Default Value

|+takeBeforeTest+
|take a screenshot after page loading, that is calling +WebDriver.get(String)+
|false
|+takeAfterTest+
|take a screenshot as the last action in the test execution
|false
|+takeWhenTestFailed+
|take a screenshot only when the test failed
|true 
|+rootDir+
|folder where all screenshots will be placed
|target
|+baseDir+
|folder inside the root folder where the screenshots be placed
|screenshots
|+screenshotType+
|type of taken image
|PNG

|===

In order to know how to configure Arquillian Reporter extension which is embedded into Droidium screenshooter, check https://github.com/arquillian/arquillian-recorder/blob/master/README.adoc[this documentation].
