= Arquillian Droidium Native

Arquillian Droidium Native plugin for Arquillian Droidium container provides necessary infrastructure 
for container implementation needed for testing of native application on Android device via 
http://dominikdary.github.io/selendroid/[Selendroid] project. 

In a nutshell, it looks into your application you want to test (APK file) and it modifies 
Selendroid server accordingly (to be more detailed, its AndroidManifest.xml). After these changes,
it is resigned once again since the content of APK has changed and it installs modified Selendroid 
server and application under test (_aut_) into Android device. _Aut_ is instrumented by Selendroid 
server.

You can use good-old WebDriver from Selenium to carry out the tests since Selendroid implements 
WebDriver API - the biggest advantage under the sun.

== Configuration

From Maven point of view, you have to put this artifact together with Android container artifact on classpath 
while testing:

----
<dependency>
    <groupId>org.arquillian.extension</groupId>
    <artifactId>arquillian-droidium-native-depchain</artifactId>
    <version>${droidium.version}</version>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

You have to register extension in `arquillian.xml` by putting this snippet into it:

----
<!-- Support for Arquillian Droidium Native extension 
    for testing native Android applications via Selendroid -->
<extension qualifier="droidium-native">
    <!-- path you your selendroid-server.apk -->
    <property name="serverApk">selendroid-server.apk</property>
</extension>
----

You have to download Selendroid server APK from Selendroid project manually and put it 
on classpath. It will be recognized by this extension then. Note the qualifier for 
this extension - `droidium-native`.

== Configuration properties

==== serverApk
===== default: selendroid-server.apk

Sets path to Selendroid server APK from Selendroid project which is dynamically installed on target device for 
translating WebDriver calls to Android browser and back. Selendroid server is repacked according to application 
under test (_aut_) to reflect its base package for instrumentation needs.

----
<property name="serverApk">/path/to/your/selendroid/server/apk</property>
----
